# Generated by Django 4.1.5 on 2023-08-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('established_at', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=100)),
                ('established_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authapp.company')),
                ('emp_departmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authapp.scale'),
        ),
    ]
