# Generated by Django 4.1.5 on 2023-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0002_remove_department_established_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ManyToManyField(to='Authapp.company'),
        ),
    ]
