# Generated by Django 4.1.5 on 2023-08-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0003_remove_department_company_department_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_departmet',
            field=models.ForeignKey(default='System Engineer', on_delete=django.db.models.deletion.SET_DEFAULT, to='Authapp.department'),
        ),
    ]
