# Generated by Django 4.1.5 on 2023-08-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0004_remove_department_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_departmet',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
